services:
  random-api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'neixin/random-pic-api'
    volumes:
# 竖屏图片
        - './portrait:/var/www/html/portrait'
# 横屏图片
        - './landscape:/var/www/html/landscape'
    ports:
        - '1000:80'
    restart: always